### PR TITLE
Change instantdata userconfig

### PR DESCRIPTION
**Pull request by ppenguin**
Changed to a fork of `instantdata` which offers the option `--get-userconfig-dir=<confdir>` to enable to use personal overrides for files normally only obtained from `...-instantDotfiles-unstable/share/instantdotfiles/<confdir>`.

Added one use case that overrides the `appmenu` config to `~/.config/rofi` if available.

(This can be used to fix the fontsize issues mentioned in https://github.com/instantOS/instantOS/issues/90)

### CODE REVIEW

**Comment by SCOTT-HAMILTON** [comment]
Just made a test suite for instantdata. It just checks that instantdata gives the good system paths. To run the test, use `nix-build -A tests.instantdata` with the latest commit from dev.

Could you update the `pkgs/tests/instantdata/default.nix` file accordingly ? If any help is needed, don't hesitate to ask here.

**Comment by con-f-use** [comment]
Can we instead get that repo into the instantOS project here on github? @SCOTT-HAMILTON @ppenguin

**Comment by SCOTT-HAMILTON** [comment]
Sure, but I think that only @paperbenni can give me the permissions (temporarly) to move my repo to instantOS.

**Comment by con-f-use** [comment]
> Sure, but I think that only @paperbenni can give me the permissions (temporarly) to move my repo to instantOS.

@SCOTT-HAMILTON any progress on that?

**Comment by SCOTT-HAMILTON** [comment]
I'll merge to move on. We will transfer instantdata later. 

Anyway thanks a lot for your work and patience @ppenguin !
It really took too long to be merged and this kind of delay shouldn't happen in the future if we don't want people to be discouraged every time they open a new PR.

**Pull request merged**
